name: PHPStan

on:
  pull_request:
    branches: [ main ]

jobs:
  phpstan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v5

      - name: PHPStan Static Analysis
        uses: php-actions/phpstan@master
        with:
          path: app/ resources/ routes/ tests/
